databases:
  - name: e_kardex
    databaseName: e_kardex
    user: e_kardex

services:
  - type: web
    name: e_kardex
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn e_kardex.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e_kardex
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
