# Generated by Django 4.1.1 on 2022-10-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex_app', '0002_kardex_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='bedNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='doctorInCharge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='hospitalName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='hospitalNum',
            field=models.IntegerField(null=True),
        ),
    ]
